### ISSUE TITLE
Implement the Card array generation logic

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#1]
# Description
We need to implement the card generation logic in the deck.js file. This is a crucial part of our application as it will be responsible for creating the deck of cards that will be used in the game.

Please refer to [deck.js](https://github.com/shivansh-bhatnagar18/multiplayer-uno/blob/master/backend/uno-game-engine/deck.js)

## Task
The array `deck` should be populated with the cards as per the rules of the game, in the structure mentioned in the comment.

**Comment by sethdivyansh** [comment]
![image](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/59174836/93b7929b-dbaa-4e98-8785-35a91980862c)
@kuv2707 In this dummy code `deck.push(makeCard('special', 'wild', 'wild'))`, the second 'wild' is being passed as the color, but 'wild' is not a valid color; it is a type or value.

**Comment by sethdivyansh** [comment]
I want to work on this issue. Please assign me.

**Comment by sethdivyansh** [comment]
@kuv2707 
What is the color of wild cards?
In dummy code it is wild but there is no color as wild in `CardColor` (in types.d.ts). 

Do we need to add a color type to `CardColor`? If so, should it be black, as wild cards are described as black in the UNO card description?
<img width="477" alt="image" src="https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/59174836/8c705bbc-352c-40cb-9297-65fcf28f5845">
<img width="520" alt="image" src="https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/59174836/13b19900-9b62-46ec-8887-1ef2d65bc0a6">

**Comment by kuv2707** [comment]
You can add the an entry in the type as required. The color property will never be used anyway in the context of wildcards.
