### ISSUE TITLE
Implement the About Us page 

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [shivansh-bhatnagar18/multiplayer-uno#100]
**Describe the bug**
The hamburger menu in the landing page contains About Us button which is non functional

**To Reproduce**
Use the modal created for the Join Existing Game button to create a modal for the rules. Note that please don't change the size of modal much but use overflow. Write something about the project and about COPS/CSOC.

**Comment by Abhishek-Punhani** [comment]
@csoc-bot claim

**Comment by kuv2707** [comment]
@swetagit186 Can you provide some content for the about us page?

**Comment by shruti862** [comment]
Content for the About Page ::
Welcome to our Multiplayer UNO Game website where our aim is to bring the joy of UNO to the digital realm, allowing friends and families to connect and play this beloved card game from anywhere in the world. It is  a passion project developed under the CSOC’24 (COPS Summer of Code) initiative by COPS.
CSOC is one of our flagship programs, designed to provide students with hands-on coding experience during the summer break. Participants engage in a variety of projects, ranging from web development to machine learning, all while being mentored by experienced members of the COPS community. This Multiplayer UNO Game is one of the exciting outcomes of CSOC, showcasing the talent and dedication of our participants.
 COPS is an enthusiastic community of developers and programmers dedicated to fostering a culture of coding and innovation. It provides a collaborative environment where students can enhance their programming skills, work on real-world projects, and contribute to open-source initiatives.
We invite you to join us in this exciting journey. Whether you are here to play UNO, provide feedback, or become a part of our vibrant community, we welcome you with open arms. Let's connect, code, and create together!
For more information about COPS and our initiatives, visit our official website https://www.copsiitbhu.co.in/.
Thank you for visiting, and we hope you enjoy your time playing UNO!
