### ISSUE TITLE
Fix the responsiveness of the homepage

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [shivansh-bhatnagar18/multiplayer-uno#101]
**Describe the bug**
The homepage currently has a background that shrinks in low-width devices

**To Reproduce**

- [ ] Fix the homepage for mobile devices
- [ ] Add breakpoints to fix the modal for small devices so it looks okayish
- [ ] Any other things that you thing needs change related to the responsiveness (mention in your PR)

**Comment by asmit27rai** [comment]
@csoc-bot claim

**Comment by realnilesh** [comment]
@csoc-bot-claim

**Comment by realnilesh** [comment]
@csoc-bot claim

**Comment by ritwik-69** [comment]
i am working on this issue
