### ISSUE TITLE
Change the title and the logo

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [shivansh-bhatnagar18/multiplayer-uno#104]
**Describe the bug**
Currently the name of the project shows Vite + React + TS. You are required to change it to the default project name and change its logo to any suitable logo related to UNO
![image](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/117429248/554cd7ce-d956-4989-ad60-c53a293a423a)

**Comment by realnilesh** [comment]
csoc-bot-claim

**Comment by ritwik-69** [comment]
@csoc-bot claim
