### ISSUE TITLE
Style the scrollbars throughout the app

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#108]
# Description
It would be nice to have a funky scrollbar too.

![image](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/88523649/f3ef91b6-cbe1-4e18-93a6-1dc5d875153b)

Feel free to add what you find suitable, and we'll provide feedback on it if changes should be made.

**Comment by MuskanPastor** [comment]
@csoc-bot claim

**Comment by realnilesh** [comment]
@csoc-bot claim

**Comment by realnilesh** [comment]
> @realnilesh This issue has been successfully assigned to y #112

**Comment by realnilesh** [comment]
#112  PR has been made

**Comment by realnilesh** [comment]
#118 PR has been made in another pull request
