### ISSUE TITLE
Improve the structure of the modal

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#116]
# Description
The modal component in `library` directory was supposed to be as reusable as possible, but ended up catering to a particular use case. In other places where modals were needed, we made duplicate modals tailored to that use case only. All these modals have some common features which can be extracted into one actually reusable and configurable modal component.
- Clicking on the blurred area closes the modal.
- The styles of all the modal containers are the same.
- Some modals need buttons, others don't.
- The `ESC` key closes the modal (tracked separately)

Lets start with these for now. We should have a `ModalContainer` library component which accepts the following as props:
- The modal content
- An array of buttons to be displayed at the bottom.

We should have a context for the modal in the same way we have for toasts.

We should be able to use it like this:
```ts
function HomePage(){
const modal = useModal(<div>Hi there</div>,[<Button/>]);
return <div onClick={()=>modal.show()}></div>
}
```
**Any action (click etc) on the buttons passed to the modal will close the modal.**

# Notes
- Following the commit adding the modal context, refactor all the existing modals to use the newly created modal system.
- We currently have modals for:
  - Asking join game code.
  - Rules
  - About us

**Comment by ritwik-69** [comment]
@csoc-bot claim

**Comment by realnilesh** [comment]
@csoc-bot claim
