### ISSUE TITLE
Show hosted game code/url

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#117]
# Description
When a user creates (hosts) a game, the game page should show a modal with the joining link/ game code for the current game.
There should also be a button to start the game.

# Blockers
- [x] #116

**Comment by realnilesh** [comment]
@csoc-bot claim

**Comment by asmit27rai** [comment]
@csoc-bot claim

**Comment by Abhishek-Punhani** [comment]
@csoc-bot claim

**Comment by kuv2707** [comment]
@Abhishek-Punhani Note that this issue should only be worked on after its blockers are cleared

**Comment by kuv2707** [comment]
@Abhishek-Punhani This issue is now unblocked
