### ISSUE TITLE
Improve the navbar

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#122]
# Description
The navbar links are hardcoded. Also, some links open modals, others redirect.
We can pass the link texts and callbacks which navigate or open modals etc. as an array as a prop
This will make the navbar more flexible.

# Blockers
- #121

**Comment by PrathamX595** [comment]
@kuv2707 this issue has #121 as a blocker does that mean any restrictions or should I start work on #121?

**Comment by kuv2707** [comment]
@PrathamX595 The blocker is cleared, it can be worked on now

**Comment by kuv2707** [comment]
@PrathamX595 What's the status on this?

**Comment by PrathamX595** [comment]
@kuv2707 I am working on it, am facing some time problems due to an internship but will put a PR by Sunday night.

**Comment by draunger** [comment]
@kuv2707 can I work in this??

**Comment by PrathamX595** [comment]
> @kuv2707 can I work in this issue?? 

I have done all the work PR will be posted as soon as my laptop will be back
