### ISSUE TITLE
Make a client side event dispatcher

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#124]
# Description
Following the server-side handling of game events, there should be a module in the frontend which applies the events on the client-side game state.

This would help reduce the amout of data transferred to the client to update the state.

- Since we trust all data coming from the server, we can omit some validation which we currently do in the backend.
- Effectively, we need a *dispatcher function* which accepts the current game state and a `GameEvent` and changes the game state as per the event. The function can reside in a new module `clientDispatch.ts`.
- We plan to later use this function with the `useDispatch` hook, so it should be made compatible to that.

# Notes
- Refer to how an event is handled in the backend. The frontend implementation should mirror it, while reducing the data validation we do in the backend. 
- Any error encountered in the backend was handled and a message was returned, but we expect things to always work in the frontend, and so can throw Errors if something goes wrong.
- When we initially receive the full game state from the server, we should create data structures to retrieve the cards and players by their ids. We can then use them in the dispatcher.

**Comment by vivekmaurya001** [comment]
@csoc-bot claim

**Comment by kuv2707** [comment]
@vivekmaurya001 What's the status?

**Comment by vivekmaurya001** [comment]
I was not able to do much progress in this ,I m unassigning it

**Comment by Abhishek-Punhani** [comment]
@csoc-bot claim

**Comment by kuv2707** [comment]
Make sure you completely understand the whole "event system" and how we use long polling before working on this
You can utilize the discussions forum to ask queries (or whatsapp :| )
