### ISSUE TITLE
Fix the Toast Bug

### ISSUE THREAD

**Issue by ritwik-69** [shivansh-bhatnagar18/multiplayer-uno#127]
**Describe the bug**
The Navbar component is not letting you close the Toast component properly.    

**Reproduce the Bug**
Click on Start game button and a toast will be generated at the center top 
when you try to close it it won't close 

**screenshot**
![image](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/72665321/606a1dba-ba3d-4201-8ae6-341d303ea106)

**Comment by sethdivyansh** [comment]
@ritwik-69  how to reproduct this issue?

**Comment by ritwik-69** [comment]
It just the z index of navbar is on top of the toast component.due to which we are not able to click the cross div in toast

**Comment by kuv2707** [comment]
Please attach a ss of the bug in the issue description

I am assigning it to you, you can make a pr for it
