### ISSUE TITLE
Implement throwing cards on the frontend

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#130]
# Description
It would make sense to click on a card to throw it. Throwing a card just involves a function call to `channel.triggerEvent`.

We can add intricacies such as rearranging cards etc later on.

**Comment by kuv2707** [comment]
This issue is suitable for newcomers

**Comment by draunger** [comment]
@kuv2707 i did not understand the exact problem can you describe further more please

**Comment by kuv2707** [comment]
A preliminary implementation of this has been made by me
