### ISSUE TITLE
Implement fading in and out on the modal and sidebar

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#131]
# Description
The elements should fade in instead of appearing abruptly. The same goes for when it is hidden - it should fade out.

We'd want to implement it completely using CSS (preferably tailwind). A duration of `300ms` seems fine.
Currently, when the sidebar is closed, the component is unmounted altogether, which would make the fade out animation difficult. We can just set `display:none` on it, instead of not rendering it when closed.

**Comment by kuv2707** [comment]
This issue is suitable for newcomers

**Comment by Lavina-11** [comment]
@csoc-bot claim

**Comment by Spikoftw** [comment]
@csoc-bot claim

**Comment by realnilesh** [comment]
@csoc-bot claim

**Comment by Lavina-11** [comment]
@csoc-bot abandon

**Comment by AB000001** [comment]
@csoc-bot claim

**Comment by kuv2707** [comment]
@AB000001 What's the status?

**Comment by AB000001** [comment]
I am able to implement the fade in while opening. But fad out while closing is not happening

**Comment by kuv2707** [comment]
I think its likely due to the fact that we are not rendering the component when we close it. We should instead render it even then and make it invisible with css (decided by the state variable).

You can make a PR with the existing progress. Also, it is totally fine to feel stuck, you can engage in discussions with the maintainers for the same.

**Comment by AB000001** [comment]
Sure Thanks. let me try

**Comment by kuv2707** [comment]
@AB000001 You should reach out if you're stuck somewhere

**Comment by kuv2707** [comment]
@AB000001 Unassigning due to inactivity.

**Comment by sksmagr23** [comment]
@csoc-bot claim
