### ISSUE TITLE
Implement handling the `ANNOUNCE_UNO` event on the backend

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#132]
# Description
Please refer to the events already implemented in the events directory in the game engine.

- You'd need to decide the data payload for this event, and accordingly update the `types.ts`
- There are many corner cases and easily imagined bugs to be taken care of.

**Comment by sethdivyansh** [comment]
@csoc-bot claim

**Comment by asmit27rai** [comment]
@csoc-bot claim
