### ISSUE TITLE
Add the Rules for setting up the password

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [shivansh-bhatnagar18/multiplayer-uno#133]
**Describe the bug**
The user while signing up does not know what is the criteria for setting up the password

**To Reproduce**
Check the password requirements from the backend and write them down in the sign up page

![Screenshot from 2024-06-20 17-50-00](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/117429248/37fd8049-b829-412d-ae92-4cef9352aa6c)

**Comment by Lavina-11** [comment]
@csoc-bot claim

**Comment by Lavina-11** [comment]
@csoc-bot claim

**Comment by samarsrivastav** [comment]
@csoc-bot claim'

**Comment by Sweetdevil144** [comment]
Hi @shivansh-bhatnagar18  bhaiya 😊😊 I'd like to work on this Issue !!

**Comment by shivansh-bhatnagar18** [comment]
@Sweetdevil144 Maintain karna hai kya?
