### ISSUE TITLE
Fix flicker when trying to create a game without logging in

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#142]
# Description
When clicking on 'Create Game" without logging in, the screen flickers and a toast is displayed. This is because the GameProvider on mounting checks the auth state and returns if not logged in. 

We can fix this flicker by checking it in the homepage itself, before navigating to the game page.
(We should leave the GameContext undisturbed)

**Comment by kuv2707** [comment]
This issue is suitable for first timers

**Comment by sethdivyansh** [comment]
@kuv2707 Also JoinGameModal appears on clicking start game without logging in.

https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/59174836/2f9eec8b-88ae-4e36-82ae-d4cbc772e5ee

**Comment by kuv2707** [comment]
Yes, i know.
That modal has its own problems, to be handled separately

**Comment by Spikoftw** [comment]
csoc-bot claim

**Comment by Spikoftw** [comment]
@csoc-bot claim
