### ISSUE TITLE
Implement the `CHALLENGE_UNO` event in the game engine

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#145]
# Description
Now that we have implemented the `ANNOUNCE_UNO` event, we can also add the `CHALLENGE_UNO` event, which is triggered by players when a player didn't announce uno while they had time.

- Do add tests verifying the logic and functionality
- Refer to the events directory in `uno-game-engine` for context on how to implement game event handlers.

**Comment by kuv2707** [comment]
@sethdivyansh Assigning it to you since you have recently worked on this area.
You can unassign if this doesn't seem to be a good fit.

**Comment by sethdivyansh** [comment]
@kuv2707 yes sure.

**Comment by sethdivyansh** [comment]
@csoc-bot claim
