### ISSUE TITLE
Implement the `START_GAME` event handler in the engine

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#148]
# Description
This event can only be triggered by the host of the game, who is the first player in the players array of the game.
The following occurs on triggering this event:
- The game `status` is changed to `RUNNING`
- Cards are distributed to all the joined players (there's a function in `GameEngine` which handles that)

# NOTES
- Refer to how other event handlers are implemented in the `events` directory.
- Be mindful of corner cases and easily imagined bugs.

**Comment by ritwik-69** [comment]
@csoc-bot claim
