### ISSUE TITLE
Add support for replying to messages in `Message` box

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#153]
# Description
We need to add a way to select a message to be replied. The design is subject to discussion.
The implementation is mostly there:
- The `ChatMessage` type has a field `ref` which stores the id of the message the current message is referring to.

# Possible design
Perhaps we can make it so that clicking on a message selects it for replying, and when sending the message, we include the selected message's id in the `ref` field. 
When displaying a message, we can take the content of the message `ref` is pointing to, and truncate it to around 20 characters, and display it in a dark css filter before the actual message content.

**Comment by kuv2707** [comment]
@shivansh-bhatnagar18 Please take care of the design and UX that should be there for this.

**Comment by ritwik-69** [comment]
@csoc-bot claim
