### ISSUE TITLE
Display the player whose turn it is currently

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#157]
# Description
We should display the name of the player having the current turn. We can also highlight/add backdrop css filters on the cards of the player.

- We can display the current player's name here
![image](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/88523649/bfe92863-a246-40d2-a11f-713d5d35f298)

- We have access to it via the current player index in the client gameState and the players array

**Comment by asmit27rai** [comment]
@csoc-bot claim

**Comment by kuv2707** [comment]
@asmit27rai assigned
