### ISSUE TITLE
Display player names along with cards

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#158]
# Description

- We can add the player name in a suitable place around their card count.
![image](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/88523649/ad2e26dc-01df-47bb-83ad-a9a4683fb94e)

- We should refactor out the JSX responsible for rendering the player cards etc into its own `Player` component.
- We should be able to use it like:
```
<Player player={gameState.players[i]} highlighted={true} />
```
The `highlighted` prop highlights the player if it is their turn.

**Comment by draunger** [comment]
csoc-bot claim

**Comment by kuv2707** [comment]
@draunger You can take up #130 since this one is being worked on inadvertently in #165

**Comment by asmit27rai** [comment]
> @asmit27rai This is related to your work
OK
