### ISSUE TITLE
Make the `UNO` button functioning

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#159]
# Description
The `UNO` button presently in the game page is dummy.
The button should trigger the `ANNOUNCE_UNO` event.
Use `channel.triggerEvent` for triggering events with appropriate payload.

**Comment by draunger** [comment]
@csoc-bot claim

**Comment by draunger** [comment]
@csoc-bot abandon

**Comment by Abhishek-Punhani** [comment]
@csoc-bot claim
