### ISSUE TITLE
Add a button to display game properties

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#161]
# Description
We display the `GamePropertiesModal` on entering the game, but only once. 
- We should have a button to open this modal anytime.
- We should also add a `LEAVE GAME` button to this modal, which triggers the `LEAVE_GAME` event (using `channel.triggerEvent`) and navigates to the homepage.
- The position of the game properties button is not decided. Use your intuition.

# Notes
- The two changes mentioned above should be in two separate commits.

**Comment by sksmagr23** [comment]
@csoc-bot claim

**Comment by sksmagr23** [comment]
Bhaiya can you please tell from where to import and trigger leave game event,I am a bit confused about it

**Comment by kuv2707** [comment]
You can use `channel.triggerEvent` to trigger an event. You need to pass the data relevant to the event (as defined in `types.ts`). For the `LEAVE_GAME` event though, no additional data is needed.

Look at `MessageInput.tsx`, where we trigger the `SEND_MESSAGE` event
![image](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/88523649/628c4ba5-51c5-4b0c-8b83-97b605a15d3b)

Let me know if you have any further questions
