### ISSUE TITLE
Design a Navbar component

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#19]
Refer to [this file](https://github.com/shivansh-bhatnagar18/multiplayer-uno/blob/master/frontend/src/Navbar.tsx)

# Expected functionality

- The logo to be displayed should be passed as a prop (link to the image file relative to the assets folder)
- The links to be displayed should be passed as a prop (An array of objects, each containing the link text and href).
- Background should be customizable through props: for now, lets keep the background a linear gradient, whose color points will pe passed through props.

The props should be optional and appropriate default values should be used.

**Comment by criticic** [comment]
for the frontend, is it planned to use a css framework like tailwind etc, or pure css?

**Comment by Abhishek-Punhani** [comment]
can i work on this issue?

**Comment by rsnj5** [comment]
Hi, I'd like to work on this issue. I am somewhat familiar with it. Can you please assign it to me?

**Comment by RashiJyotishi** [comment]
I would like to work on this issue.

**Comment by asmb123** [comment]
I would like to work on this issue.

**Comment by shiviiish** [comment]
I would like to work on this issue

**Comment by RashiJyotishi** [comment]
please review my PR..

**Comment by chandraabhinandan** [comment]
I would like to work on this issue

**Comment by MoCkZeTa** [comment]
can i work on this issue?

**Comment by Ankit-Pradhan04** [comment]
I would like to work on this issue

**Comment by Abhinaba-Chatterjee** [comment]
I would like to work on this issue

**Comment by Abhinavaggarwal7** [comment]
Can you please assign this issue to me?

**Comment by moksh1tha** [comment]
i would like to work on this issue

**Comment by shivansh-bhatnagar18** [comment]
The issue you are trying to assign to yourself is already assigned.
