### ISSUE TITLE
Implement card shuffling logic

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#2]
# Description
The shuffle function is intended to shuffle the elements of the given array in place. However, it currently only swaps the first two elements, which is not a proper shuffling algorithm. The function should be updated to implement a generic shuffling algorithm.

# Current Code Snippet
```javascript
/**
 * This function shuffles the elements of the given array *in place*. The function behaves in a type-agnostic way.
 * Time complexity: O(n)
 * @param {Array} deck 
 */
function shuffle(deck) {
    //todo: Implement a generic shuffling algorithm
    [deck[0], deck[1]] = [deck[1], deck[0]];
}

```
 
# Tasks
 Research and select a suitable generic shuffling algorithm (e.g., Fisher-Yates shuffle).
 Implement the chosen shuffling algorithm within the shuffle function.
 Ensure the function behaves in a type-agnostic manner.
 Write unit tests to verify the correctness of the implemented shuffling algorithm. (Optional for now)
 Update the function's documentation if necessary.
# References
[Fisher-Yates Shuffle on Wikipedia](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle)
# Related Issues
N/A
# Notes
The current implementation only swaps the first two elements, which is incorrect and does not fulfill the purpose of shuffling.

**Comment by sethdivyansh** [comment]
i want to work on this issue.
