### ISSUE TITLE
Design a button component

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#20]
Refer to [this file](https://github.com/shivansh-bhatnagar18/multiplayer-uno/blob/master/frontend/src/library/button.tsx)

# Description
Design and implement a reusable `Button` component that can be used in different parts of the application. The button should be highly customizable and handle click events effectively. 

It also makes sense to export some default configurations using this component, like `DangerousActionButton`, `OkayButton` etc.
We can add more as per the need of the project.

# Requirements
1. Customization Options:
* Background color
* Text color
* Border color
2. Size Options:
* Small
* Medium
* Large
3. Shape Options:
* Rectangle
* Rounded
* Circle

# Functionality:
* Handle click events

# Notes
- Ensure that the component is designed to be reusable and flexible for various use cases within the application.
- Include documentation and examples on how to use the Button component with different customization options.
- Try not to use any external dependency. Use tailwind for styling as much as possible.

**Comment by asmit27rai** [comment]
Hey @kuv2707, I want to work on this issue.

**Comment by ritwik-69** [comment]
I would like to work on this issue.

**Comment by rsnj5** [comment]
Can i work on this issue?

**Comment by PrathamX595** [comment]
I would like to work on this issue

**Comment by Lokeshranjan8** [comment]
@shivansh-bhatnagar18  i would like to work on this

**Comment by chandraabhinandan** [comment]
I would like to work on this.

**Comment by chandraabhinandan** [comment]
I would like to work on this.

**Comment by shiviiish** [comment]
I would like to work on this.

**Comment by Ankit-Pradhan04** [comment]
I would like to work on this issue

**Comment by MoCkZeTa** [comment]
I would like to work on this issue.

**Comment by moksh1tha** [comment]
i would like to work on this issue
