### ISSUE TITLE
Design an error page

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#21]
Refer to [this file](https://github.com/shivansh-bhatnagar18/multiplayer-uno/blob/master/frontend/src/pages.tsx/Error.tsx)

# Requirements
When an unknown route is accessed, an error page is rendered. 
The page should inform the user that they tried to access an invalid route, and provide a link to the homepage.

**Comment by kuv2707** [comment]
@Shubham-Khetan-2005 This issue requires tailwind to be set up in the project. Once we do that, I'll assign it to you. 

You can remind us in case we forget.

**Comment by Shubham-Khetan-2005** [comment]
@kuv2707 A reminder to assign me the issue as tailwind set-up is done.

**Comment by asmb123** [comment]
I would like to work on this issue.

**Comment by kuv2707** [comment]
As decided later (and informed in the groups), you can drop a message here indicating that you are working on this, and start with it. Your message will only be there to indicate to others about how many people are working on it.

**Comment by PrathamX595** [comment]
I am working on this issue

**Comment by shivansh-bhatnagar18** [comment]
@kuv2707 Can you please recommend the error page that looks suitable for our project? From PR #34 and #35.

**Comment by kuv2707** [comment]
#34 seems more "modern" imo.

The choice depends on the overall look we are aiming for.. which i want to stay out of.

**Comment by moksh1tha** [comment]
i would like to work on this issue

**Comment by shivansh-bhatnagar18** [comment]
The issue you are trying to assign to yourself is already assigned.

**Comment by criticic** [comment]
bot not working?
