### ISSUE TITLE
Design UI components and pages

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#22]
[Figma file](https://www.figma.com/design/QThXVzJp8ImlCNi0P6M8nx/Untitled?node-id=0-1&t=sjbBOMfbSAXC3zwp-1)

This is a master issue tracking the development of various UI components which are used throughout the application.

We are in a way making our own framework. The directory `src/library` contains components which we will use throughout the application.
The directory `src/pages` contain components which make use of the library components to render the pages mapped to the router in `App.tsx`.

Reusing components from  `src/library` will bring a uniformity in the UI. That said, the components should be flexible enough to be used at different places(ie, should be configurable via props)

Designing a component includes writing styles, implement the logic for its functionality etc.

### Library components
- [x] #76 
- [x] #67 
- [x] #68 
- [x] #77 

### Page components

- [x] #21 
- [x] #23 
- [x] #79 
- [x] #78 
- [x] #95 

# Notes
- When adding a component to the `src/library` directory, refactor the application to use that component wherever possible. (This will be done in the commit following the implementation of the library component).
- Make the components as flexible and reusable as possible.
- All design related discussions are being held in [this whatsapp group](https://chat.whatsapp.com/IAHNjqSHvG85RCSh6H7KCj)

**Comment by sksmagr23** [comment]
Can I look after this?

**Comment by kuv2707** [comment]
@sksmagr23 You are supposed work on the sub-issues mentioned here. This issue is only there to track the overall progress.

**Comment by shivansh-bhatnagar18** [comment]
Thanks for taking this issue! Let us know if you have any questions!

**Comment by kuv2707** [comment]
This issue is not meant to be assigned to anyone. Please work on the sub-issues
