### ISSUE TITLE
Design `PlayOptions` page

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#23]
Refer to [this file](https://github.com/shivansh-bhatnagar18/multiplayer-uno/blob/master/frontend/src/pages/PlayOptions.tsx)

# Description
The `/play` route renders a component which gives the user an option to either join an existing game or start their own new game.

# Deliverables
- A form for both the options. A skeleton is already present in the file. Leave event handlers empty for now. Once the backend is ready, the event handlers will be updated with the endpoints.
- Use components from `src/library` or add components (which will potentially be reused) there before using in the page.

**Comment by rsnj5** [comment]
can i work on this issue?

**Comment by sksmagr23** [comment]
I am also working on it

**Comment by Lokeshranjan8** [comment]
@shivansh-bhatnagar18  Should I also implement a 'Join' button when users enter their code

**Comment by Abhinavaggarwal7** [comment]
Can you please assign this issue to me?

**Comment by moksh1tha** [comment]
i would like to work on this issue

**Comment by PrathamX595** [comment]
I would like to work on it

**Comment by ritwik-69** [comment]
I would like to work on this

**Comment by shivansh-bhatnagar18** [comment]
The issue you are trying to assign to yourself is already assigned.
