### ISSUE TITLE
Convert module to TypeScript: `engine.js`

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#25]
# Description
This module is central to the whole game logic and must be converted to TypeScript early on.

## Notes
- The Player type should be an object with `id`. Additional properties will be decided after implementing other parts of the application.

**Comment by criticic** [comment]
I'd like to work on this!

**Comment by sksmagr23** [comment]
There is a error, running backend server due to uninstalled ts-dev dependencies

**Comment by criticic** [comment]
can you share complete logs?
