### ISSUE TITLE
Error while starting backend server 

### ISSUE THREAD

**Issue by sksmagr23** [shivansh-bhatnagar18/multiplayer-uno#39]
**Describe the error**
While running npm start, it shows error that .ts is not identified ,but I have installed the required dependencies.

**Screenshots**

![Screenshot from 2024-06-01 18-54-23](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/153260291/c3b9b241-01d6-4fe9-a68d-438ad9a458a9)
![Screenshot from 2024-06-01 18-58-33](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/153260291/15a656ff-9a29-483f-a133-87c2d120add0)

**Comment by criticic** [comment]
Sync your master branch with the upstream's master branch, a change was pushed I think, to solve this very issue. Also dont make changes on your master branch.

You can read this file: [CONTRIBUTING.md](https://github.com/shivansh-bhatnagar18/multiplayer-uno/blob/master/CONTRIBUTING.md)

**Comment by sksmagr23** [comment]
I have synced it, and matched the code with repo ,but error still persists

**Comment by criticic** [comment]
You'll see on your fork it says 14 commits ahead, I think there might have been some issues. Also compare the backend/package.json file here and in your repository, *If you have no changes in your master branch you'd like to keep*

1) Add the upstream remote pointing to this repo, and then fetch it
2) Then hard reset it to the upstream version

**Comment by sksmagr23** [comment]
Thank you, it worked now.
