### ISSUE TITLE
Make it possible to uniquely identify cards

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#4]
# Description
The `makeCard` function in `deck.js` should assign a unique id to each card to ensure each card can be uniquely identified.

# Current Code Snippet
```javascript
/**
 * Helper function to make a card object.
 * @param {string} type one of ['number', 'special', 'wild']
 * @param {string} color one of ['red', 'yellow', 'green', 'blue']
 * @param {string} value the numeric value as string or the special card name ("skip", "reverse", "draw2", "wild", "draw4")
 * @returns {{type: string, color: string, value: string, id: unknown}} card - An object representing an UNO card.
 */
function makeCard(type, color, value) {
    //todo: Implement unique identification of cards by assigning an id to each card
    return { type, color, value };
}
```
# Expected Output
Each card object returned by makeCard should include a unique id property.

Some discussion is needed on the type of unique identification used. We can choose from UUID, random numbers etc.
Please propose your approach here and you will be assigned accordingly.

# Notes
* Ensure the id is unique for every card created.
* Update the JSDoc accordingly.

**Comment by criticic** [comment]
While UUID is not a bad option, it would probably not make sense for us, considerng there are only 108 possible options. And we'd need to save this information somewhere.

Instead we could use a certain scheme so that the id itself encodes some information, so something like red-skip, blue-reverse, green-2

**Comment by shivansh-bhatnagar18** [comment]
@kuv2707 Could you please suggest what sort of unique-id should we prefer to assign to the cards

**Comment by kuv2707** [comment]
#14 Provides a viable solution.

The problem with uuids is that they would be a little slow, and since we only have a very bounded and predictable set of 108 cards, it makes sense to use a simpler id generation scheme. Also, it saves us from adding a dependency.
