### ISSUE TITLE
Implement the route handler for `/events`

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#45]
# Context and Description
In long polling, the client sends `GET` request, which is then witheld by the server till there is an event to propagate.
A skeletal layout of this has been implement.
The `POST` request on the same endpoint should trigger event propagation to all the connected clients.
There should be a logic to filter which clients to propagate the event to.

Refer to [this file](https://github.com/shivansh-bhatnagar18/multiplayer-uno/blob/master/backend/eventRecipients.ts).
You might need to define a function to return all connected clients.

# Tasks
- Implement the `POST` handler for the `/events` endpoint, which relays the event object to all the eligible clients.
- Define a function which filters the eligible clients. For now, it should allow all clients to receive events.

# Notes
- The handler should be implemented in `gameControllers.ts`.

**Comment by sksmagr23** [comment]
I would like to work on it

**Comment by asmit27rai** [comment]
I want to work on this issue

**Comment by ritwik-69** [comment]
i would like to work on this

**Comment by vivekmaurya001** [comment]
i would like to work on this
