### ISSUE TITLE
Implement game state management

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#5]
# Description
The `gameStore.js` module is responsible for setting and retrieving the game state. The following functionalities need to be implemented:

1. `createGame` Function

- Generate a unique game ID.
- Store the game instance in the games map.

2. `retrieveGame` Function

- Retrieve the game instance from the games map using the provided game ID.

# Current Code Snippet
```javascript
// This module is responsible for setting and retrieving the game state.
import { GameEngine } from './uno-game-engine/engine';
const games = map();

export function createGame() {
    //todo: generate a unique game id and store
}

/**
 *
 * @param {string} id Game id
 * @returns {GameEngine|null} GameEngine instance
 */
export function retrieveGame(id) {
    //todo: Retrieve the game from the store
}
```
# Expected Output

- createGame: Should generate a unique game ID and store the game instance in the games map.
- retrieveGame: Should retrieve and return the game instance corresponding to the given game ID from the games map. If no game is found, return null.

# Notes
- Ensure that the game IDs are unique.
- Handle cases where the game ID does not exist in the store.

**Comment by Sweetdevil144** [comment]
Hello @kuv2707 sir. I'd like to work on this Issue. Can you assign this to me?

**Comment by kuv2707** [comment]
@Sweetdevil144  Babu tere se nahi hoga. Tu spelling mistakes thik kar docs me 💃
