### ISSUE TITLE
Implement game event management system

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#6]
# Description

The handler for endpoint `/events` is responsible for dispatching game events like `THROW_CARD`, `ANNOUNCE_UNO`, etc.

# Task

Implement the handler (in gameController.js) and write logic to process an event object to update the game state.
## For game events
The handler should retrieve the appropriate GameEngine object responsible for the particular game the client is a part of,
and forward the event to be handled by the engine. It should then send the engine's response back to the client.

## For non-game events
This would be implemented later. We can decide to add a chatbox or other means of interaction.

# Notes
- Regularly check `ARCHITECTURE.md` for any updates on the structure of the system. 

# Blockers 
The game engine should at least be able to process the `JOIN_GAME` event before we start with this.
That again, depends on auth system working properly, tracked in #62 .

**Comment by criticic** [comment]
I'd like to work on this, though what events need to be implemented?

**Comment by rsnj5** [comment]
can i work on this?

**Comment by kuv2707** [comment]
This issue has mostly been solved by me.
