### ISSUE TITLE
Implement the enqueuing mechanism for clients

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#60]
# Description
We should store all the events to be sent to a client in a queue, and empty the queue when we have a response object available. 
We need to use a queue because if we immediately try to sent the events, it is possible that the client has not sent another polling request at the time of sending events, leading to the events being sent nowhere, and never reaching the client.

# Notes
- Refer to [this file](https://github.com/shivansh-bhatnagar18/multiplayer-uno/blob/master/backend/eventRecipients.ts).
- Make arrangements for easily imaginable corner cases.

**Comment by ritwik-69** [comment]
i would like to work on this issue
