### ISSUE TITLE
Implement the actual sending of events.

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#61]
# Description
The events are sent through the `doSendEvent` function in [`eventRecipients.ts`](https://github.com/shivansh-bhatnagar18/multiplayer-uno/blob/master/backend/eventRecipients.ts).

The response body should only contain the events array for now.

# Notes
- Mind easily imagined corner cases and bugs.

**Comment by shivansh-bhatnagar18** [comment]
Thanks for taking this issue! Let us know if you have any questions!

**Comment by shivansh-bhatnagar18** [comment]
The issue you are trying to assign to yourself is already assigned.

**Comment by ritwik-69** [comment]
i would like to work on this issue

**Comment by ritwik-69** [comment]
@kuv2707 I think i made some error while pull request as my earlier commit is also present for some reason

**Comment by kuv2707** [comment]
You can `drop` the unwanted commit. Refer to contributing.md.
