### ISSUE TITLE
 Implement JWT Authentication for User login and registration

### ISSUE THREAD

**Issue by GitMasterJatin** [shivansh-bhatnagar18/multiplayer-uno#62]
# Description:
We need to implement JWT authentication in our application. This should be done using React for the frontend, Node.js and Express for the backend, and MongoDB for the database.

# Specs
- A `UserModel` should be created at `models/userModel.ts`. You can use the `mongoose` library.
Currently, it suffices to add the fields `name` and `password` to it.
- There should be an authentication middleware, which adds `user` object to the Request object.
- There should be handlers for `/login` and `/register`, possibly sharing the verification logic with the middleware.
- The user should be signed in immediately after registering.

# Notes
- Please refer to `ARCHITECTURE.md` before starting any work.

**Comment by GitMasterJatin** [comment]
I want to work on this issue.

**Comment by kuv2707** [comment]
I'll provide a plan on how we wish to organize the code soon.
We can start working on it then.

**Comment by ritwik-69** [comment]
I would like to work on this

**Comment by Abhishek-Punhani** [comment]
I would like to work on this

**Comment by kuv2707** [comment]
This issue is ready to be worked on, and is a priority.

**Comment by shivansh-bhatnagar18** [comment]
The issue you are trying to assign to yourself is already assigned.

**Comment by asmit27rai** [comment]
I would like to work on this issue

**Comment by shivansh-bhatnagar18** [comment]
The issue you are trying to assign to yourself is already assigned.
