### ISSUE TITLE
Design customizable Heading component.

### ISSUE THREAD

**Issue by ApoorvDubey23** [shivansh-bhatnagar18/multiplayer-uno#67]
# Description
Design a reusable Header component that can be used in different parts of the application. It should be highly customizable .
The component should be created in the `src/library` directory.

# Input Fields
The component should accept the following as props:
- Font Size
- Font Weight
- Font style

# Notes
- Add more input fields if necessary.
- Use tailwind for styling as much as possible.
- Ensure the component is reusable.

**Comment by shivansh-bhatnagar18** [comment]
Thanks for taking this issue! Let us know if you have any questions!

**Comment by ApoorvDubey23** [comment]
> What elements be included in this header, only title or some other?

Only Title

**Comment by shivansh-bhatnagar18** [comment]
The issue you are trying to assign to yourself is already assigned.
