### ISSUE TITLE
Design a Toast Component.

### ISSUE THREAD

**Issue by ApoorvDubey23** [shivansh-bhatnagar18/multiplayer-uno#68]
# Description
Design a customizable toast component which can be used in various parts of the project.
# Requirements

## Functionality

- The component should take input for a message to be displayed.
- We should be able to choose the background color of the toast. (We can set some predefined configurations, like `Toast.INFO`, `Toast.ERROR`, `Toast.WARNING` etc).
- Should be able to set the duration for which the toast appears on the screen (Predefined durations would bring uniformity)
- The component should offer different location options for displaying the toast:
   - Top-Left
   - Top-Right
   - Top-Center

# Note
- Consider including an animation effect for showing and hiding the toast.
- This component is effectively our implementation of the `react-toastify` library.
- Use react contexts in the implementation.

**Comment by ritwik-69** [comment]
i would like to work on this issue

**Comment by asmit27rai** [comment]
I Want To Work On This Issue.
