### ISSUE TITLE
Design a wireframe on Figma

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [shivansh-bhatnagar18/multiplayer-uno#72]
**Describe the bug**
Currently, there is no design that everyone is following so it leads to creation a visually mismatched web app

**To Reproduce**
All the assignees are requested to collaborate and create a WhatsApp group or something where we'll be working on developing the designs of our project on Figma. Do add me as well on that group so that we can finish the design prospect of this project within a day or two.

**Comment by PrathamX595** [comment]
I would like to work on it

**Comment by RashiJyotishi** [comment]
Below link is for whatsapp group for design of web app https://chat.whatsapp.com/IAHNjqSHvG85RCSh6H7KCj

**Comment by shivansh-bhatnagar18** [comment]
Thanks for taking this issue! Let us know if you have any questions!

**Comment by kuv2707** [comment]
Further discussions on design would be done in the whatsapp group.
