### ISSUE TITLE
Design a button component

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [shivansh-bhatnagar18/multiplayer-uno#76]
**Describe the bug**
Design a button component for the homepage of the UNO 

**To Reproduce**
Create two coloured versions of the button as shown in the given figma file
 https://www.figma.com/design/QThXVzJp8ImlCNi0P6M8nx/Untitled?node-id=0-1&t=sjbBOMfbSAXC3zwp-1

**Screenshots**
![Screenshot from 2024-06-07 21-36-15](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/117429248/2d9a3211-44fe-41fd-8310-44757bdb3348)
![Screenshot from 2024-06-07 21-36-56](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/117429248/2b7c2596-fd53-4fbc-acb4-81cd0037515f)

**Comment by shivansh-bhatnagar18** [comment]
Thanks for taking this issue! Let us know if you have any questions!

**Comment by sksmagr23** [comment]
Bhaiya do I create two button component or make input props

**Comment by shivansh-bhatnagar18** [comment]
Making input props would be better. Try creating a color prop for the same.

**Comment by kuv2707** [comment]
There is already a `Button.tsx` in `library` directory where the changes should be made.

**Comment by shivansh-bhatnagar18** [comment]
The issue you are trying to assign to yourself is already assigned.
