### ISSUE TITLE
Design an input component

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [shivansh-bhatnagar18/multiplayer-uno#77]
**Describe the bug**
Design the input component which will help in taking inputs from the user

**To Reproduce**
You can take help from https://www.figma.com/design/QThXVzJp8ImlCNi0P6M8nx/Untitled?node-id=0-1&t=YAndgenntSfWnMd0-0

**Screenshots**
![Screenshot from 2024-06-07 21-37-10](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/117429248/31c552d7-ffd6-47cd-b16b-2ea6f165de54)

**Comment by shivansh-bhatnagar18** [comment]
Thanks for taking this issue! Let us know if you have any questions!

**Comment by PrathamX595** [comment]
which aspects of the input component do we need to be customizable or should it be a generic one ?

**Comment by shivansh-bhatnagar18** [comment]
The issue you are trying to assign to yourself is already assigned.
