### ISSUE TITLE
Create the HomePage Component of the UNO page

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [shivansh-bhatnagar18/multiplayer-uno#78]
**Describe the bug**
Design the home page along with the hamburger menu

**To Reproduce**
YOu can take help from the design in https://www.figma.com/design/QThXVzJp8ImlCNi0P6M8nx/Untitled?node-id=0-1&t=YAndgenntSfWnM

**Screenshots**
![Screenshot from 2024-06-07 21-37-24](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/117429248/f90b7ff4-219c-4042-afde-e2019eebaa84)
![Screenshot from 2024-06-07 21-37-37](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/117429248/8781cedc-24d7-427c-9a4d-6374f17054c8)
![Screenshot from 2024-06-07 21-37-43](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/117429248/9e38b688-e210-4748-b930-384e0a37e811)

**Comment by shivansh-bhatnagar18** [comment]
Thanks for taking this issue! Let us know if you have any questions!

**Comment by shivansh-bhatnagar18** [comment]
@sksmagr23 Just to confirm that this will be the landing page of our project.

**Comment by sksmagr23** [comment]
Bhaiya what to do of the playoptions page created before?

**Comment by shivansh-bhatnagar18** [comment]
We have to replace that page anyways.

**Comment by sksmagr23** [comment]
Bhaiya do I implement landing page  now, or after pages modification?

**Comment by shivansh-bhatnagar18** [comment]
The button component is ready now so you can begin with the homepage work. Thanks
