### ISSUE TITLE
Design the Login Page and the  Sign In Page 

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [shivansh-bhatnagar18/multiplayer-uno#79]
**Describe the bug**
Design the login page and the sign in page for the game and create the required workflow

**To Reproduce**
Take design inspirations from https://www.figma.com/design/QThXVzJp8ImlCNi0P6M8nx/Untitled?node-id=0-1&t=YAndgenntSfWnMd0-0

**Screenshots**
![Screenshot from 2024-06-07 21-38-03](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/117429248/c8a5aa9a-99ba-4c95-b282-74a6225b2e82)

**Comment by shivansh-bhatnagar18** [comment]
Thanks for taking this issue! Let us know if you have any questions!

**Comment by shivansh-bhatnagar18** [comment]
Thanks for taking this issue! Let us know if you have any questions!

**Comment by shivansh-bhatnagar18** [comment]
The issue you are trying to assign to yourself is already assigned.

**Comment by PrathamX595** [comment]
@shivansh-bhatnagar18 should I wait for the input and button components or start assuming they are merged ?

**Comment by shivansh-bhatnagar18** [comment]
@PrathamX595 Start working on creating the page. Button component is ready baaki input components bhi ho jaayenge mp. Nhi hue toh ek aur issue banake fix karr denge
