### ISSUE TITLE
Improve card drawing logic

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#8]
# Description
The `drawCardFromDeck` function in  [engine.js](https://github.com/shivansh-bhatnagar18/multiplayer-uno/blob/master/backend/uno-game-engine/engine.js#L35) should handle the scenario when the deck is empty. If the deck is empty, the thrown cards (maintained in another array) should be moved back to the deck before drawing a card for the player.

# Current Code Snippet
```js
drawCardFromDeck(player) {
    //todo: Handle the case when the deck is empty and we have to move the thrown cards back to the deck
    this.players.find(p => p.id === player.id).cards.push(this.cardDeck.pop());
}
```

# Expected Output
- The function should handle the case where this.cardDeck is empty.
- When the deck is empty, the thrown cards should be shuffled and moved back to the deck.
- The player should then be able to draw a card from the reshuffled deck.
# Notes
- Ensure that the reshuffling of the thrown cards maintains the game's integrity.

**Comment by asmit27rai** [comment]
I want to work on this issue...

**Comment by Abhishek-Punhani** [comment]
Can I work on this issue?

**Comment by ritwik-69** [comment]
can i be assigned this issue?

**Comment by aayush0325** [comment]
id love to work on this issue

**Comment by criticic** [comment]
Whoever is solving this, make sure to also handle the case where there is no player with the given id, as after converting to typescript in #33  we get this warning:
`Object is possibly 'undefined'.ts(2532)`, due to find returnign undefined if a match is not found.
