### ISSUE TITLE
Implement the JoinExistingGame Component

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [shivansh-bhatnagar18/multiplayer-uno#84]
**Describe the bug**
The Home page contains a join game button which should open a modal which has to be implemented

**To Reproduce**
See the figma file https://www.figma.com/design/QThXVzJp8ImlCNi0P6M8nx/Untitled?node-id=0-1&t=Qq1Kq0yqVsYuBs14-0

**Screenshots**
![Screenshot from 2024-06-08 15-42-29](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/117429248/4606e529-d768-4bcf-9fcf-c0a64982a601)

**Comment by asmit27rai** [comment]
I would like to work on this issue.

**Comment by kuv2707** [comment]
@asmit27rai feel free to use the bot to claim an issue (`/assign`)

**Comment by shivansh-bhatnagar18** [comment]
The issue you are trying to assign to yourself is already assigned.

**Comment by kuv2707** [comment]
> The issue you are trying to assign to yourself is already assigned.

Whoa smarty
