### ISSUE TITLE
frontend: Use `useNavigate` hook for programmatically navigating between pages.

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#89]
# Description
The frontend makes use of `window.location.href` in various places for navigation, which is not good for performance. We should use the proper way to do it, which is through the `useNavigate` hook.

**Comment by sksmagr23** [comment]
@csoc-bot claim

**Comment by RashiJyotishi** [comment]
@csoc-bot claim
