### ISSUE TITLE
Add game event handler for `DRAW_CARD` event.

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#92]
# Description
Following the pattern of `THROW_CARD`, we need to have a handler for the `DRAW_CARD` event. This should reside in a file in `uno-game-engine/events`.

# Specs
The event handler should validate the event, apply it on the respective game, and return a result indicating whether the event was successfully applied or some error occured.

# Notes
- Be mindful of subtle corner cases and bugs.
- Take the existing handlers as a reference to know how handlers are supposed to work.

**Comment by valak70** [comment]
@csoc-bot-claim

**Comment by valak70** [comment]
@csoc-bot abandon

**Comment by MuskanPastor** [comment]
@csoc-bot claim

**Comment by Abhishek-Punhani** [comment]
@csoc-bot claim

**Comment by kuv2707** [comment]
@Abhishek-Punhani It is not a good practice to put PRs on issues not assigned to you!
It got overlooked by me, but  be sure not to interfere in others' work henceforth.

@MuskanPastor Sorry for this, hope you find another issue.
