### ISSUE TITLE
Add game event handler for `LEAVE_GAME` event

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#94]
# Description
Following the pattern of `THROW_CARD`, we need to have a handler for the `LEAVE_GAME` event. This should reside in a file in `uno-game-engine/events`.

# Specs
The event handler should validate the event, apply it on the respective game, and return a result indicating whether the event was successfully applied or some error occured.
The leaving player's cards should be restored to the deck, and the deck should be shuffled.

# Notes
- Be mindful of subtle corner cases and bugs.
- Take the existing handlers as a reference to know how handlers are supposed to work.
- Refer to the type of the event object for the event.

**Comment by ritwik-69** [comment]
@csoc-bot claim

**Comment by ritwik-69** [comment]
@csoc-bot claim

**Comment by asmit27rai** [comment]
@csoc-bot claim

**Comment by kuv2707** [comment]
@ritwik-69 If you wish to work on a PR not assigned to you, you can leave a message letting others know you are working on it, and tag a maintainer to get it assigned to you.
