### ISSUE TITLE
Implement the Game page

### ISSUE THREAD

**Issue by kuv2707** [shivansh-bhatnagar18/multiplayer-uno#95]
# Description
This is the most complex part of the project.

# Specs
The page should roughly have this appearance:
![Imagen de WhatsApp 2024-06-11 a las 23 04 54_6e19a05d](https://github.com/shivansh-bhatnagar18/multiplayer-uno/assets/88523649/33c8ada0-9b7e-4134-a842-541f2f8f33af)

We primarily focus on functionality, and can later tweak the design as seems fit.

- We should set up a game context, storing the current game state. The context also handles the polling requests, updating game state with the server data etc. That in turn, should be done after some basic game events are handled in the backend.

**Comment by sksmagr23** [comment]
@csoc-bot claim

**Comment by sksmagr23** [comment]
@kuv2707 this page should render at which route?

**Comment by kuv2707** [comment]
@kuv2707 So here's an outline:
- After choosing whether to host/join a game, the user is redirected to `/game` with the choice passed as a query param.
We map the `/game` route to a component which first reads from the params and makes api calls for the same. For example, if the user wishes to host a game, an api call for that will be made (yet to be implemented on the backend), and an initial game state would be returned, which the client will then use to render the players, their cards, etc.

Concurrently, a polling request will be sent to the server and the whole event management system should be set up.

I think it would make sense to handle all using a `GameContext`. The actual Game component will then retrieve the players and their cards from the context and render the UI. The Game component will only be rendered once the initial game state is received from the server (whether hosting or joining a game).



This seems too huge, so it would require many further discussions on the implementation, and can encompass many plan changes.

**Comment by sksmagr23** [comment]
Ok , I will start implementing things one by one, once the login/signup component is merged

**Comment by kuv2707** [comment]
It would be encouraged if you are open with any problems you face or something in the implementation or architecture you didn't understand - or some suggestion to improve/simplify things. These discussions can be done preferably on the whatsapp group (or sometimes DM)

Once you open a PR, further discussions can be done there. You can "review" your own code and comment on a block of code which warrants maintainers' attention.

**Comment by PrathamX595** [comment]
@kuv2707 I would like to co contribute on this issue

**Comment by kuv2707** [comment]
@PrathamX595 Please go ahead, for some reason i am not able to assign this

**Comment by kuv2707** [comment]
ah done
