### ISSUE TITLE
Implement the rules modal

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [shivansh-bhatnagar18/multiplayer-uno#99]
**Describe the bug**
The hamburger menu in the landing page contains rules button which is non functional

**To Reproduce**
Use the modal created for the Join Existing Game button and Rules from chatGPT to create a modal for the rules. Note that please don't change the size of modal much but use overflow.

**Comment by ritwik-69** [comment]
@csoc-bot claim

**Comment by kuv2707** [comment]
@ritwik-69 refer to architecture.md for a link to the rules we aim to follow

**Comment by shivansh-bhatnagar18** [comment]
Gr8 work @ritwik-69
